/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8.1/samples
 */
plugins {
    kotlin("jvm") version "1.3.50"
}

repositories {
    jcenter();
}

dependencies {
    implementation("com.beust:klaxon:5.0.1")
    implementation("junit:junit:4.12")
    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
}
